### PR TITLE
Add basic usage docs

### PR DESCRIPTION
**Pull request by LukeWeidenwalker**
Based on our discussion today I've added a basic example for how to use this to the README + a demo notebook to show how this implements the mini-backend capability in `examples/`!

Let me know what you think!

### CODE REVIEW

**Review by bschumac — COMMENTED** [review]
For me all good. Minor thing on the networkx graph plot is that the name for the multiply node is cut off. If possible maybe add a margin to the plot to ensure that the node names can be seen.

**Comment by ValentinaHutter** [comment]
Looks very good! You could add a note in the `README.md` that says "An example of using `openeo-pg-parser-networkx` together with `openeo-processes-dask` can be found in [openeo-pg-parser-networkx](https://github.com/Open-EO/openeo-pg-parser-networkx/tree/EODCAPI-99-add-documentation-to-show-mini-backend-capability)/[examples](https://github.com/Open-EO/openeo-pg-parser-networkx/tree/EODCAPI-99-add-documentation-to-show-mini-backend-capability/examples)/01_minibackend_demo.ipynb)."

**Comment by LukeWeidenwalker** [comment]
> For me all good. Minor thing on the networkx graph plot is that the name for the multiply node is cut off. If possible maybe add a margin to the plot to ensure that the node names can be seen.

Fair point - however I just spent 10 minutes trying to fix this, didn't find a fix yet and don't really want to spend more time on this right now! ;)

**Comment by LukeWeidenwalker** [comment]
> > For me all good. Minor thing on the networkx graph plot is that the name for the multiply node is cut off. If possible maybe add a margin to the plot to ensure that the node names can be seen.
> 
> Fair point - however I just spent 10 minutes trying to fix this, didn't find a fix yet and don't really want to spend more time on this right now! ;)

Ah, stumbled across a quick fix after all: https://github.com/Open-EO/openeo-pg-parser-networkx/pull/11 :D

**Pull request merged**
